apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-resources-claim
spec:
  storageClassName: "nfs-client"
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany